#:schema node_modules/wrangler/config-schema.json
name = "simpleposttor2-hono-app"
main = "src/index.tsx"
compatibility_date = "2024-08-06"

#[[d1_databases]]
#binding = "DB" # i.e. available in your Worker on env.DB
#database_name = "posts-d1"
#database_id = "b0dd00e2-d26a-4051-a0fb-868c5e04b484"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "images"

#MY_VARIABLE = "unique" # i.e. available in your Worker on env.MY_VARIABLE


